# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TheDailyMe' do

pod 'CVCalendar', '~> 1.2.8'

end

target 'TheDailyMeTests' do

end

target 'TheDailyMeUITests' do

end

